#!/bin/bash

# ***********************************************
#  Backup config esx server
#  Date: 10.08.2022
#  v1.00
#  Authors:
#  Vladimir Svishch (IndianBiker)  <mail:5693031@gmail.com>
#  https://github.com/BikerIndian/Bash/esx-beckup-config
# ***********************************************


ip_file=ip.txt

read -p 'Username: ' username
read -sp 'Password: ' password

while read line
do
./bin/backup-esx $line $username $password
done < $ip_file